spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: root  
    password: s3cur3
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate: 
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
